### ISSUE TITLE
scibet_R function not working

### ISSUE THREAD

**Issue by anishamarysunil** [PaulingLiu/scibet#10]
Hello! My team is trying to implement scibet for automated cell-type annotation. I'm following the tutorial and I'm using the example data (http://scibet.cancer-pku.cn/document.html) to understand how the tool works. when I tried using the scibet_R function to train the dataset, it gave me the following error: 
![Screenshot 2022-04-12 181407](https://user-images.githubusercontent.com/59005928/162944312-f0df6d60-2e9d-4c7d-9231-83e2885a581b.png)
could you please help me with this issue? Thanks in advance.

**Comment by FanZhang9** [comment]
i have the same error, what happening?
